[profile.default]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
evm_version = "paris"
src = "contracts"
out = "foundry-artifacts"
cache_path = "cache/foundry"
test = "test/foundry"
via_ir = false

libs = ["node_modules", "./contracts/"]
allow_paths = ["node_modules", "./contracts/"]

remappings = [
	"@openzeppelin/contracts-v5/=node_modules/@openzeppelin/contracts-v5/",
	"@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@concero/=node_modules/@concero",
    "@chainlink/=node_modules/@chainlink/",
    "@uniswap/=node_modules/@uniswap/",
    "sushiswap-v3-periphery/contracts/=node_modules/sushiswap-v3-periphery/contracts/",
    "forge-std/=node_modules/forge-std/",
    "contracts/=contracts/",
]
